services:
  postgres:
    image: postgres:16
    container_name: kcgi-postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: assign03_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: